# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
